core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = patterns('',
   url(r'^$', Home.as_view(), name='home'),
   url(r'^user/',include('registration.backends.simple.urls')),
   url(r'^user/',include('django.contrib.auth.urls')),
   url(r'^review/create/$', login_required(ReviewCreateView.as_view()), name='review_create'),
   url(r'review/$', login_required(ReviewListView.as_view()), name='review_list'),
   url(r'^review/(?P<pk>\d+)/$', login_required(ReviewDetailView.as_view()), name='review_detail'),
   url(r'^review/update/(?P<pk>\d+)/$', login_required(ReviewUpdateView.as_view()), name='review_update'),
   url(r'^review/delete/(?P<pk>\d+)/$', login_required(ReviewDeleteView.as_view()), name='review_delete'),
   url(r'^review/(?P<pk>\d+)/reply/create/$', login_required(ReplyCreateView.as_view()), name='reply_create'),
   url(r'^review/(?P<review_pk>\d+)/reply/update/(?P<reply_pk>\d+)/$', login_required(ReplyUpdateView.as_view()),name='reply_update'),
   url(r'^review/(?P<review_pk>\d+)/reply/delete/(?P<reply_pk>\d+)/$', login_required(ReplyDeleteView.as_view()), name='reply_delete'),
   url(r'^vote/$', login_required(VoteFormView.as_view()), name='vote'),
   url(r'^user/(?P<slug>\w+)/$', login_required(UserDetailView.as_view()), name='user_detail'),
   url(r'^user/update/(?P<slug>\w+)/$', login_required(UserUpdateView.as_view()), name='user_update'),
   url(r'^user/delete/(?P<slug>\w+)/$', login_required(UserDeleteView.as_view()), name='user_delete'),
   url(r'^search/$', login_required(SearchReviewListView.as_view()), name='search'),
   )

track_review/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls')),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
RATING_CHOICES = (
(0, 'None'),
(1, '*'),
(2, '**'),
(3, '***'),
(4, '****'),
(5, '*****'),
)

import os
import uuid

def upload_to_location(instance, filename):
    blocks = filename.split('.')
    ext = blocks[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    instance.title = blocks[0]
    return os.path.join('uploads/', filename)
# Create your models here.
class Review(models.Model):
    Track = models.CharField(max_length=300)
    Review = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    rating = models.IntegerField(choices=RATING_CHOICES, default=0)
    image_file = models.ImageField(upload_to=upload_to_location, null=True, blank=True)

    def __unicode__ (self):
        return self.Track

    def get_absolute_url(self):
        return reverse("review_detail", args=[self.id])

class Reply(models.Model):
    review = models.ForeignKey(Review)
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

    def __unicode__(self):
      return self.text

class Vote(models.Model):
    user = models.ForeignKey(User)
    review = models.ForeignKey(Review)

    def __unicode__(self):
        return "%s upvoted" % (self.user.username)

templates/review/review_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<p class="lead">Are you sure you want to delete your review of "{{ review.Track }}"?</p>
<form method="post" action="">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Delete</button>
</form>
{% endblock %}

templates/review/review_detail.html
{% extends 'base.html'%}
{% block content %}
<h1>{{ review.Track }}</h1>
<p>{% if review.image_file %}<img src="{{ review.image_file.url }}" />{% endif %}</p>
{% if rating.rating__avg < 0.5 %}
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  ({{ rating.rating__avg }})
{% elif rating.rating__avg < 1.5 %}
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  ({{ rating.rating__avg }})
{% elif rating.rating__avg < 2.5 %}
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  ({{ rating.rating__avg }})
{% elif rating.rating__avg < 3.5 %}
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  ({{ rating.rating__avg }})
{% elif rating.rating__avg < 4.5 %}
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  ({{ rating.rating__avg }})
{% else %}
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  ({{ rating.rating__avg }})
{% endif %}
<p>{{ review.Review }}</p>
{% if review.user == user %}
<p>Reviewed by <a href="{% url 'user_detail' slug=review.user.username %}">{{ review.user.username }}</a> on {{ review.created_at }}</p>
<p><a href="{% url 'review_update' pk=review.id %}">Edit review</a></p>
<p><a href="{% url 'review_delete' pk=review.id %}">Delete review</a></p>
{% endif %}
{% if replies.count > 0 %}
<h3>{{ replies.count }} Reply{{ replies.count|pluralize }}:</h3>
{% endif %}
{% for reply in replies %}
<div class="panel">
  <p>{{ reply.text }}</p>
  {% if reply.user == user %}
  <p><a href="{% url 'reply_update' review_pk=review.id reply_pk=reply.id %}">Edit reply</a></p>
  <p><a href="{% url 'reply_delete' review_pk=review.id reply_pk=reply.id %}">Delete reply</a></p>
  {% endif %}
  <p><a href="{% url 'user_detail' slug=reply.user.username %}">{{reply.user.username }} Replied</a></p>
</div>
{% endfor %}
<p><a href="{% url 'reply_create' pk=review.id %}">Reply here</a></p>
{% endblock %}

templates/review/review_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class="row">
  <div class="col-lg-6">
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
      <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
</div>
{% endblock %}

templates/review/review_list.html
{% extends 'base.html' %}
{% block content %}
{% for review in object_list %}
<div class="panel">
  <h3><a href="{{ review.get_absolute_url }}">{{ review.Track }}</a></h3>
  <p>Reviewed by <a href="{% url 'user_detail' slug=review.user.username %}">{{ review.user.username }}</a> on {{ review.created_at }}</p>
  <p>{{ review.vote_set.all.count }} Vote{{ review.vote_set.all.count|pluralize }}</p>
  <form method="post" action="{% url 'vote' %}">
      {% csrf_token %}
      <input type="hidden" name="review" value="{{ review.id }}" />
      <input type="hidden" name="user" value="{{ user.id }}" />
    <button>+</button>
  </form>
</div>
{% empty %}
<p>No results found.</p>
{% endfor %}
{% if is_paginated %}
<nav>
    <ul class="pager">
        {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
      {% endif %}
      {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
      {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock %}